name: CI

on:
  push:
  pull_request:

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install config-file-validator
        run: go install github.com/Boeing/config-file-validator/v2/cmd/validator@latest

      - name: Validate config files
        run: ~/go/bin/validator .